"""DB 진입점."""

from stock_compass.db.migrations import MIGRATIONS, migrate
from stock_compass.db.repository import (
    AlertRow,
    HistoryRow,
    NewsSummaryRow,
    get_cached_news_summary,
    get_db_connection,
    get_last_score,
    get_latest_scores,
    get_previous_composite_score,
    get_recent_alerts,
    get_recent_news_summaries,
    get_score_history,
    get_scores_on_date,
    get_ticker_id,
    get_today_token_usage,
    has_daily_alert_today,
    has_recent_alert,
    record_alert,
    record_token_usage,
    upsert_composite_score,
    upsert_news_summary,
    upsert_ticker,
)

__all__ = [
    "MIGRATIONS",
    "AlertRow",
    "HistoryRow",
    "NewsSummaryRow",
    "get_cached_news_summary",
    "get_db_connection",
    "get_last_score",
    "get_latest_scores",
    "get_previous_composite_score",
    "get_recent_alerts",
    "get_recent_news_summaries",
    "get_score_history",
    "get_scores_on_date",
    "get_ticker_id",
    "get_today_token_usage",
    "has_daily_alert_today",
    "has_recent_alert",
    "migrate",
    "record_alert",
    "record_token_usage",
    "upsert_composite_score",
    "upsert_news_summary",
    "upsert_ticker",
]
